services:
  app-typescript-compiler:
    build:
      context: .
      dockerfile: ./bin/docker/node/Dockerfile
    container_name: app-typescript-compiler-container
    volumes:
      - .:/app
    command: sh -c "npm install && tail -f /dev/null"
    tty: true