services:
  application_nginx:
    ports:
      - 80:80
    build: ./nginx/
    restart: unless-stopped
    volumes:
      - ../frontend/:/usr/share/nginx/html/
    container_name: application_nginx_container
  application_alpine:
    tty: true
    build: ./alpine/
    restart: unless-stopped
    container_name: application_alpine_container
    volumes:
      - ../frontend/:/workspace/
      - ../data/:/root/.npm/_logs/
      - ./alpine/build.go:/workspace/build.go
      - ./alpine/package.json:/workspace/package.json
      - ./alpine/tsconfig.json:/workspace/tsconfig.json
