services:

  application_aider:
    profiles:
      - aider
    tty: true
    build: ./aider
    env_file:
      - ./aider/.env
    volumes:
      - ../:/workspace/
    restart: unless-stopped
    working_dir: /workspace/
    extra_hosts:
      - host.docker.internal:host-gateway
    container_name: application_aider_container
    environment:
      - OLLAMA_API_BASE=http://host.docker.internal:11434

  application_esbuilder:
    tty: true
    working_dir: /workspace/
    build: ./esbuilder/Dockerfile
    container_name: application_esbuilder_container
    volumes:
      - workspace:/workspace/
      - ../web/:/workspace/web/:Z
      - ./workspace/build.go:/workspace/build.go:Z
      - ./workspace/global.ts:/workspace/global.ts:Z
      - ./workspace/package.json:/workspace/package.json:Z

  application_typescript:
    tty: true
    working_dir: /workspace/
    build: ./typescript/Dockerfile
    container_name: application_typescript_container
    volumes:
      - workspace:/workspace/
      - data:/root/.npm/_logs/
      - ../web/:/workspace/web/:Z
      - ./workspace/global.d.ts:/workspace/global.d.ts:Z
      - ./workspace/package.json:/workspace/package.json:Z

  application_nginx:
    ports:
      - 80:80
    image: nginx:alpine
    restart: unless-stopped
    working_dir: /usr/share/nginx/html/
    extra_hosts:
      - host.docker.internal:host-gateway
    container_name: application_nginx_container
    volumes:
      - data:/var/log/nginx
      - ../web/build/:/usr/share/nginx/html/:Z
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:Z

  application_ngrok:
    profiles:
      - ngrok
    ports:
      - 4040:4040
    env_file:
      - ./ngrok/.env
    depends_on:
      - application_nginx
    restart: unless-stopped
    image: ngrok/ngrok:latest
    command: [ "http", "application_nginx:80" ]
    container_name: application_ngrok_container

volumes:
  data:
  workspace:
